# Generated by Django 4.0.3 on 2022-03-25 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField(blank=True, null=True)),
                ('body', models.CharField(max_length=15000)),
                ('total_votes', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(blank=True, null=True)),
                ('bio', models.CharField(max_length=15000)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/article')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profileUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150, null=True)),
                ('body', models.CharField(max_length=15000)),
                ('total_votes', models.IntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profileQuestion', to='forum.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='VoteAnswer', to='forum.answer')),
                ('emiter_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emiter_profile', to='forum.profiles')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='VoteQuestion', to='forum.question')),
                ('recever_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recever_profile', to='forum.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TagQuestion', to='forum.question')),
                ('tag_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tag', to='forum.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_one_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Friendship', to='forum.profiles')),
                ('friend_two_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Friendship2', to='forum.profiles')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profileAnswer', to='forum.profiles'),
        ),
    ]
