# Generated by Django 4.0.3 on 2022-03-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='question',
            name='profile',
        ),
    ]
