# Generated by Django 4.0.3 on 2022-03-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_answer_created_at_alter_question_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='user',
        ),
    ]
