# Generated by Django 4.0.3 on 2022-03-25 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_questionstags_question_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profileAnswer', to='forum.profiles'),
        ),
        migrations.AddField(
            model_name='question',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profileQuestion', to='forum.profiles'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='VoteAnswer', to='forum.answer')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='VoteQuestion', to='forum.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TagQuestion', to='forum.question')),
                ('tag_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tag', to='forum.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_one_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Friendship', to='forum.profiles')),
                ('friend_two_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Friendship2', to='forum.profiles')),
            ],
        ),
    ]
