# Generated by Django 4.0.3 on 2022-03-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_profiles_friendlist_alter_profiles_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='points',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
