# Generated by Django 4.0.3 on 2022-03-29 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_answer_created_at_alter_profiles_points_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
